### ISSUE TITLE
Function hangs on second call

### ISSUE THREAD

**Issue by danthegoodman1** [hajimehoshi/go-mp3#42]
I have the following part of my function:

```go
// Play mp3 file
	f, err := os.Open(fmt.Sprintf("./cachedAudio/%s-%s.mp3", spokenName, status))
	if err != nil {
		panic(err)
	}

	d, err := mp3.NewDecoder(f)
	if err != nil {
		panic(err)
	}

	c, err := oto.NewContext(d.SampleRate(), 2, 2, 8192)
	if err != nil {
		panic(err)
	}

	p := c.NewPlayer() // HERE
	if _, err := io.Copy(p, d); err != nil {
		return false, err
	}
	fmt.Println(2)

	p.Close()
	c.Close()
	f.Close()
```

When I call the function for the first time, it works fine. However any subsequent calls hang at the time marked `// HERE`. It seems as if the `NewPlayer()` function just blocks forever. When I run with goroutines, I end up getting the following error after a few calls:

`panic: oto: NewContext can be called only once`

**Comment by danthegoodman1** [comment]
If it helps these are mp3 files generated from GCP's text to speech

**Comment by hajimehoshi** [comment]
As the panic message says, NewContext cannot be called twice. You should reuse the context.

**Comment by danthegoodman1** [comment]
So I must store that variable outside the function to reuse it @hajimehoshi ? That must have slipped my mind, I assumed everything would be isolated inside the function

**Comment by hajimehoshi** [comment]
That's right. Basically one context can exist in one process.

**Comment by mdeanda** [comment]
i ran into the same but different source files are at different sample rates. is there a way to properly handle it? in my case i have the following output from simple `file` command in linux:

chimes/chime01.mp3: Audio file with ID3 version 2.4.0, extended header, contains: MPEG ADTS, layer III, v1, 128 kbps, 44.1 kHz, JntStereo
chimes/bell.mp3: Audio file with ID3 version 2.4.0, contains: MPEG ADTS, layer III, v1, 56 kbps, 44.1 kHz, Monaural
4170706c69636174696f6e206861732073746172746564d41d8cd98f00b204e9800998ecf8427e: MPEG ADTS, layer III, v2,  32 kbps, 24 kHz, Monaural

how could i play all three of these using the same context? i currently get chipmunks for some of them as they are different.

**Comment by hajimehoshi** [comment]
There is no way to play sounds with different sample rates. Please adjust the sample rate of the file(s).

**Comment by hajimehoshi** [comment]
Hm, both seems 44.1 kHz, so they should work. What error did you get?

**Comment by mdeanda** [comment]
so in my case, its a usb speaker on an old raspberry pi and i noticed the 1st sound i play after a long silence would cause speaker to flutter, so i play a silent sound first.. that was 44.1khz, then i played a chime, also 44.1, and finally a gcp sound that was at 24khz. i resampled my "built-in" sounds to 24khz and it works now.

it probably should be noted that using this library means all sounds from the app will have to be at the same sample rate -- it would have saved me a lot of time troubleshooting (and looking through old closed issues).

but thanks, the library works and is otherwise easy to use.

**Comment by hajimehoshi** [comment]
I'm confused.
* Are GCP sounds files 24kHz or 44.1kHz?
* Was there a restriction on your hardware for sample rate?

**Comment by mdeanda** [comment]
here is a simple example: http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=hello+world&tl=en

that one is 24khz. my chimes and beeps (etc.) files were 44.1. i dont have control over the 24khz files but luckily i do on the 44.1 files, so i resampled them to 24khz since i can't create multiple contexts.

**Comment by hajimehoshi** [comment]
Yeah, so Oto doesn't provide a way to play sounds that have different sample rates so far. I'll add notes about this later.

I realized this is go-mp3 repository, not Oto repository :-)
